### ISSUE TITLE
Training NERF using real-captured data

### ISSUE THREAD

**Issue by phongnhhn92** [kwea123/nerf_pl#16]
Hello,
I have followed your example to train NERF on my own data. So I have seen you and other guys have some success with single object scene (silica model). How about the real scene (fern or orchids dataset)? 

I have captured a video of my office [link](https://drive.google.com/file/d/19rjOJ4OAyb-l6DL9cKjC_59zQQo6hxR1/view?usp=sharing). However, I cant use colmap to estimate poses to train NERF model. Since you are more experienced than me on this project. Can u show me some suggestion ? It's interesting to see if this method works on real data like this.

This is the error from the colmap:
```
python imgs2poses.py ./cmvs/
Need to run COLMAP
Features extracted
Features matched
Sparse map created
Finished running COLMAP, see ./cmvs/colmap_output.txt for logs
Post-colmap
Cameras 5
Images # 6
Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/home/phong/data/Work/Paper3/Code/LLFF/llff/poses/pose_utils.py", line 276, in gen_poses
    save_poses(basedir, poses, pts3d, perm)
  File "/home/phong/data/Work/Paper3/Code/LLFF/llff/poses/pose_utils.py", line 66, in save_poses
    cams[ind-1] = 1
IndexError: list assignment index out of range
```

**Comment by kwea123** [comment]
Actually the first data I tried was real forward facing scene but due to coronavirus I can only think of my messy desktop to capture, so I didn't post it haha...
![pc](https://user-images.githubusercontent.com/11364490/83330813-b4e29e00-a2cc-11ea-839f-9a6df84163f6.gif)
It works quite well except some flickering frames, which my be due to bad lighting in the room.

Concerning your data, the photos look good, one concern is that maybe it covers too wide range that colmap cannot handle. I will take a look. If you are using local pc, you can also try to run colmap with the gui, not the `imgs2poses.py` to see what reconstruction looks like.

**Comment by kwea123** [comment]
Strange, it works perfectly using `colmap gui`. Are you able to run `colmap gui`?

**Comment by phongnhhn92** [comment]
Hi, It is weird that the script `imgs2poses.py` can not estimate the poses but the `colmap gui` is able to do it. I have tested my images using colmap gui and the sparse reconstruction works. I am trying to run Dense reconstruction to see the differences. 

Btw, how can u tell that the poses don't seem to be correct ? I have similar sparse reconstruction with you but I have no idea how to evaluate this. Can you clarify ?

Actually, I am curious on how does this NERF works on large-scale scene. For example, can we test this on large dataset such as ScanNet, Matterport or DTU dataset. 

In fact, I have capture a new set of images with lateral movement (not so much camera rotation) and this is my result. As you can see, the printer looks good but the background is not that good. My intial thought is that this NERF model doesnt work that well with far objects (like hallways). I dont know if there are any quick parameter fixes that we can change to train the model. 

![gif_optim](https://user-images.githubusercontent.com/11288381/83337033-bdcd7280-a2c0-11ea-8864-8f294e49c50d.gif)

**Comment by phongnhhn92** [comment]
Another issue is that if I am using colmap gui then how can I compute this pose_bound,npy file. I guess this is an necessary file for both training and testing.

**Comment by kwea123** [comment]
For example the 001 and 035 are almost rotated by 90 degrees, but the reconstruction looks like there's no rotation... maybe I'm wrong, it's just personal estimation.

Currently the constraint is the world space, you can only have two kinds:
1. 360 inward facing, such that the world space is a cube.
2. forward facing, such that the world space is a cuboid that **fully lies behind a certain plane**. You can see [here](https://github.com/bmild/nerf/issues/34) or some other issues in the original repo for explanation.

So complex structures like matterport won't work, since they are more like 360 **outward facing** which doesn't satisfy the above constraint. At the limit DTU still works (I tried on 1 scene) since it satisfies constraint 2.

For your new data, I reckon that the result is reasonable. As I mentioned above, the world space must be fully behind a certain plane, so anything behind that plane won't be correct, which explains the result on the left and right part (it might be due to scarce data on the edge as well).

To make it work on 360 outward facing or even more complex scenes, although I think the concept still works, it'll be lots of work:
1.  An efficient way to encode the whole space. The reason why original NeRF has the above 2 constraints is that we need to confine the coordinates into [-1, 1]^3 so that we can encode them and train efficiently. Training on 360 outward facing might require something like a spherical coordinate system to encode.
2.  An efficient way to sample the points. Different from 360 inward facing and forward facing where we know the roi lies near us, in complex scenes we need to design another way to sample the training points in 3d. Otherwise the result won't be as good in my opinion.
These are just some thoughts. Anyway I think it's a total new research topic, so there's no easy way to do that.

Finally for `poses_bounds.npy`, you can use `colmap gui` to generate sparse reconstructions first then call `imgs2poses.py` with the same argument. It will skip colmap part and only extract the bounds.

**Comment by phongnhhn92** [comment]
Thanks for your clarification ! It make sense now.

**Comment by kwea123** [comment]
@3ventHoriz0n What do you mean by "didn't complete training"? By default I only save the best 5 epochs, that's why you only have 5 ckpts at the end. Every epoch should finish normally. You can change the number here:
https://github.com/kwea123/nerf_pl/blob/f02913b8cec85ee1e65813064224270dfa9d60e1/train.py#L160

**Comment by 3ventHoriz0n** [comment]
Oh missed that part. 

Well, usually when a epoch finishes, the progress bar is replaces by next epoch. at any given time I only see one progress bar on the screen. But for the epochs I mentioned, I saw the progress bar stuck midway and for the next epoch a new progress bar would load. So I had 7 progress bars on the screen. 6 of them stuck midway and the last one for current epoch. Don't know what that means though.

**Comment by kwea123** [comment]
sometimes if you accidentally perturb the terminal (like accidentally pressed a key), it interrupts the progress bar, so a new progress bar appears and the old one will be left on the terminal and looks like it was stuck. It's just visual bug, doesn't affect training.

**Comment by 3ventHoriz0n** [comment]
Ok I seriously can't figure out what I'm doing wrong.

[Original](https://drive.google.com/drive/folders/13wM22XGwHzVRldS2j7s95m61_GjZKuoB?usp=sharing)

[Generated](https://imgur.com/a/1wjEHae)

The model doesn't seem to be learning anything at all.

**Comment by kwea123** [comment]
Can you share the sparse folder generated by colmap?

**Comment by 3ventHoriz0n** [comment]
[here](https://drive.google.com/drive/folders/1ScEVJMi1VkKTbR6pJ74s4Xp-_xtD47sb?usp=sharing)

**Comment by kwea123** [comment]
This is what I see from your training log, the center image is the prediction, I didn't see anything wrong. Also the poses seem correct. How did you generate that noisy image?
![Screenshot from 2020-06-11 22-57-13](https://user-images.githubusercontent.com/11364490/84393758-f2cdb380-ac36-11ea-90b1-0a43709d997c.png)

**Comment by 3ventHoriz0n** [comment]
I ran eval.py using checkpoint epoch=28 and dataset_name llff

**Comment by kwea123** [comment]
Maybe you forgot to add `--spheric_poses` in evaluation? Is it indeed not mentioned in readme, I will add that.

**Comment by 3ventHoriz0n** [comment]
yes I did forget to add that. I'll try again.

**Comment by kwea123** [comment]
can you share the checkpoint?

**Comment by 3ventHoriz0n** [comment]
[epoch=28](https://drive.google.com/file/d/1wHGi3EV0CHHx_wt2pLlpwhIMnOTPKmhC/view?usp=sharing)

**Comment by kwea123** [comment]
There might be need to modify these two lines in order to get good visual result:
https://github.com/kwea123/nerf_pl/blob/d41ae302dd3d186f2f12fb411d8874a1d004e00d/datasets/llff.py#L130-L131
it controls where the virtual camera is placed. This part is actually hard-coded currently, I'm still finding a way to let it adapt to various scenes. For your data I find
```
        trans_t = lambda t : np.array([
            [1,0,0,0],
            [0,1,0,-0.6*t],
            [0,0,1,0.7*t],
            [0,0,0,1],
        ])
```
is good.

**Comment by 3ventHoriz0n** [comment]
is this the camera to world matrix? Can you please explain what exactly is happening here?
Also, I uploaded all necessary files to my google drive because I wanted to run the exact-mesh notebook but when I run the cell to search for tight bounds, the runtime restarts.

**Comment by 3ventHoriz0n** [comment]
Adding `--spheric_poses` generated [this](https://drive.google.com/file/d/19cHgSz2-RqnHG8aYBY0qRdt2TlzuxeRc/view?usp=sharing) gif. Looks good except the top part has been cut off and there's a strange cloud of white dust at one location.

**Comment by kwea123** [comment]
this is the translation wrt poses center. the second line controls the height offset and the third line controls the distance offset

**Comment by 3ventHoriz0n** [comment]
ok will try the modification now.

**Comment by 3ventHoriz0n** [comment]
for the camera above, colorless mesh extraction worked perfectly. However when I tried to extract a colored mesh [this was the result](https://drive.google.com/file/d/1z5ir3x_bu-h8L0tqqaNPqZA8OnzOQsxQ/view?usp=sharing) 

What do you think is going wrong?

**Comment by kwea123** [comment]
looks like the images are rotated by 90 degrees... can you try manually rotate them by +90 (or -90) then feed to the program?

**Comment by 3ventHoriz0n** [comment]
Alright, will do that. I have faced this while reading iPhone captured images using Pillow and openCV, smh..

**Comment by 3ventHoriz0n** [comment]
I fixed the EXIF data of images and ran the experiment again. The resulting colored mesh is still not satisfactory. Any advice?

[1. Data Folder (Includes images and LLFF output files)](https://drive.google.com/drive/folders/16YTdATMbVmu1jhEnAgZ1iXeoPLXINUTV?usp=sharing)
[2. eval.py output](https://drive.google.com/file/d/1fpAP-Wa4tXRvyesookYhoIN8-pIl_glc/view?usp=sharing)
[3. .ply file](https://drive.google.com/file/d/1-JKA4pckxZ9BBEeMU8GrUE1gaar_eN9Q/view?usp=sharing)
[4. Checkpoint](https://drive.google.com/file/d/1-CCKY_FtvBxlRUTED5ljxdQDh6cTrs5x/view?usp=sharing)
[5. Colored mesh video](https://drive.google.com/file/d/1tdnbGh6Kwzug5qFKq5Z8yiXpwIekvvh_/view?usp=sharing)

**Comment by kwea123** [comment]
@3ventHoriz0n sorry, I misupdated the master code. I reverted it just now, please retry the `extract_mesh` with the same parameters, it should give good results.

**Comment by 3ventHoriz0n** [comment]
Done. Here's the [final result](https://drive.google.com/file/d/12ppA1nFCbb5dXve7RyQ_FjoHTJBnlf9R/view?usp=sharing).

**Comment by DeanChan** [comment]
Hi @kwea123, thanks for your work!

> it controls where the virtual camera is placed. This part is actually hard-coded currently, I'm still finding a way to let it adapt to various scenes.

I was wondering do you find any good way for adaptive render pose generation?
Currently I find it quite hard to set correct poses manually, therefore I'm using the interpolated c2ws from the training set. It is working but the camera movement is not satisfactory (shaky, jittering speed etc.) 
Do you have any suggestions?

**Comment by astogxl** [comment]
@kwea123，hello!
do you have  read the paper pixelNeRF? I just cant understand the part of hardcoding for generating render pose for DTU dataset.

**Comment by asbeg** [comment]
Hey!

LLFF % python imgs2poses.py ./img/           
Need to run COLMAP
Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/Users/begai/LLFF/llff/poses/pose_utils.py", line 268, in gen_poses
    run_colmap(basedir, match_type)
  File "/Users/begai/LLFF/llff/poses/colmap_wrapper.py", line 26, in run_colmap
    logfile = open(logfile_name, 'w')
FileNotFoundError: [Errno 2] No such file or directory: './img/colmap_output.txt'

**Comment by asbeg** [comment]
Hello!
I'm completely new to this topic, and I started studying. I wanted to ask if it is possible to train on the maс m1. I followed your example to train NERF on my own data, but as soon as i started `python train.py` I get the following error. Can someone help me and tell me what the problem is ? 
Is there a problem with the leptop because its based on M1?
Or need i setting up M1 Mac for PyTorch?

`python train.py \
   --dataset_name llff \
   --root_dir LLFF_DIR \
   --N_importance 64 --img_wh 504 378 \
   --num_epochs 30 --batch_size 1024 \
   --optimizer adam --lr 5e-4 \
   --lr_scheduler steplr --decay_step 10 20 --decay_gamma 0.5 \
   --exp_name exp



Traceback (most recent call last):
  File "train.py", line 178, in <module>
    profiler=hparams.num_gpus==1)
  File "/opt/homebrew/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 438, in __init__
    self.data_parallel_device_ids = parse_gpu_ids(self.gpus)
  File "/opt/homebrew/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 712, in parse_gpu_ids
    gpus = sanitize_gpu_ids(gpus)
  File "/opt/homebrew/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 678, in sanitize_gpu_ids
    """)
pytorch_lightning.utilities.exceptions.MisconfigurationException: 
                You requested GPUs: [0]
                But your machine only has: []`
