### ISSUE TITLE
Why you need a loop for chunk ?

### ISSUE THREAD

**Issue by phongnhhn92** [kwea123/nerf_pl#25]
Hello,
So I am reading your code and I am kind a curious here why you need to put a loop for the chunk parameter ? I have read the paper they they didnt mention this hyperparameter. To my understanding, in this for loop the variable i is always 1 even if batch_size B is 1024 or 2048 because the chunk is a big number 32*1024. 

Does this mean that we can set batch_size as a very big number such as 1024*1024 for multi-gpu systems ? Can u clarify on this ? 
https://github.com/kwea123/nerf_pl/blob/34bb7a9c24a6475a1cb711007a8efc4634129175/train.py#L53

**Comment by kwea123** [comment]
A batch is actually a batch of rays, and a ray is consisted of many sample points (64 for coarse by default). Therefore a batch of 1024 means there are in total 1024x64 queries to the network, which doesn't fit in a 11gb GPU, that's why we need this loop. The `chunk` size doesn't affect training outcome, it is only related to speed, so there is very little need to change this number -- I won't call it a hyperparameter.

You can set batch number to very large without crashing because the query size is always cut down to `chunk` size, but there will be two issues 1. speed 2. training performance, since too large batch size will deteriorate the result.

**Comment by phongnhhn92** [comment]
Thanks for your comment !

**Comment by LuckyOne09** [comment]
Hi,
I came across CUDA OOM when I increase batch_size. I noticed that the gpu memory will accumulate during the loop for chunk.
I changed 
```
            for k, v in rendered_ray_chunks.items():
                results[k] += [v]
```
to 
```
        for k, v in rendered_ray_chunks.items():
            v = v.cpu()
            results[k] += [v]
```
But it didn't work.
Could you give me some advice to fix it?

**Comment by kwea123** [comment]
@LuckyOne09 in training or validation? I think in validation `eval.py` I already added that. In training you cannot pass the tensors to cpu because training needs to be done on gpu. And `chunk_size` is just splitting the data into small chunks, eventually they will still be there, so the total GPU memory requirement won't change. It means the total GPU memory requirement only depends on batch_size, and changing chunk_size won't have effect.

**Comment by LuckyOne09** [comment]
OK, I understand now. Thank you for your comments!

**Comment by LuckyOne09** [comment]
@kwea123 But if GPU memory is determined by ```batch_size```, what is the point of setting ```chunk_size```, it won't save gpu memory in training.
