### ISSUE TITLE
Training NERF with DTU dataset

### ISSUE THREAD

**Issue by phongnhhn92** [kwea123/nerf_pl#27]
Hi,
I am trying to train NERF with objects from DTU dataset. I remember u said u managed to train NERF with DTU objects. So in the DTU dataset, they provide us both intrinsic and extrinsic information. For example:
```
extrinsic
0.970263 0.00747983 0.241939 -191.02 
-0.0147429 0.999493 0.0282234 3.28832 
-0.241605 -0.030951 0.969881 22.5401 
0.0 0.0 0.0 1.0 

intrinsic
361.54125 0.0 82.900625 
0.0 360.3975 66.383875 
0.0 0.0 1.0 

425.0 2.5
```
I guess this DTU dataset is similar to Blender dataset,right ? So I have 2 questions:
1) What is the focal length in the example above. I understand that that F_x = 361.54125 , F_y = 360.3975  and  they are different due to different scaling factor. Therefore, I would like to ask that in this [get_ray_directions]( https://github.com/kwea123/nerf_pl/blob/a535ee8271d2bff35602a19d1eed09fcf836bec7/datasets/ray_utils.py#L5) function, which F_x or F_y value should I use ? I think it is ok to use both and apply different value in this [line](https://github.com/kwea123/nerf_pl/blob/a535ee8271d2bff35602a19d1eed09fcf836bec7/datasets/ray_utils.py#L22),right ? Something like this:

`directions =  torch.stack([(i-W/2)/focal_x, -(j-H/2)/focal_y, -torch.ones_like(i)], -1) # (H, W, 3)`

2) Is the provided extrinsic above in the c2w format ? If it does then do I need to do any pre-processing before using it in the [get_rays](https://github.com/kwea123/nerf_pl/blob/a535ee8271d2bff35602a19d1eed09fcf836bec7/datasets/ray_utils.py#L27) function ?

**Comment by kwea123** [comment]
1. If you want to be very precise you can make this modification, the code is correct, however in practice I think it won't change much as Fx~=Fy and the calibration is not perfect. https://github.com/bmild/nerf/issues/24
2. The calibration from MVSNet is in world to camera format. Anyway I didn't use those calibration files, I ran through the same process as "llff forward-facing data" (not 360 inward facing) because it was easier and it works. If you want to use those calibration files I think it works too, but be aware of two things:
    *   change calibration format to c2w and in "right up back" coordinate https://github.com/bmild/nerf/issues/34
    *   scale the extrinsics so that the near plane is at about 1.0
https://github.com/kwea123/nerf_pl/blob/a535ee8271d2bff35602a19d1eed09fcf836bec7/datasets/llff.py#L205-L211

**Comment by phongnhhn92** [comment]
Hi,
So do you mean that u have used colmap to re-estimate the pose and bounds of the scene? 
If I understand the transformation correctly then we can just simply perform the inverse of the given w2c extrinsic to get the c2w extrinsic, right ? Will something like this will work ?
`c2w = numpy.linalg.inv(w2c)`

I guess that in case of DTU dataset then near_original = self.bounds.min() = 425.0 in my above example. If we want the nearest depth is 1.33 then what is the scale_factor should be like ? I am quite confused on this.

**Comment by kwea123** [comment]
1. Yes
2. That should do the task
3. In NeRF the input xyz (the 3d coordinate) need to be in range [-1, 1] approximately because of the positional encoding, that is why dividing by a scale is necessary. In DTU you can divide by 400 for example, which makes the range in 425/400=1.0625 to 935/400=2.3375

**Comment by smallpeachofchangan** [comment]
> Hi, So do you mean that u have used colmap to re-estimate the pose and bounds of the scene? If I understand the transformation correctly then we can just simply perform the inverse of the given w2c extrinsic to get the c2w extrinsic, right ? Will something like this will work ? `c2w = numpy.linalg.inv(w2c)`
> 
> I guess that in case of DTU dataset then near_original = self.bounds.min() = 425.0 in my above example. If we want the nearest depth is 1.33 then what is the scale_factor should be like ? I am quite confused on this.

hello, i meet the same question. Regarding the issue with DTU, have you resolved it? Now, the scale is 1/400,near and far are(1,4) the result is not good.

**Comment by smallpeachofchangan** [comment]
> 1. Yes
> 2. That should do the task
> 3. In NeRF the input xyz (the 3d coordinate) need to be in range [-1, 1] approximately because of the positional encoding, that is why dividing by a scale is necessary. In DTU you can divide by 400 for example, which makes the range in 425/400=1.0625 to 935/400=2.3375

hello, the calibration of the dtu datasets is from matlab, however,the coordinates  is (right,down,forward). Dose the rays fuc need some change? Also, the scale problem, I use the nerf model and scale=200,400. they are not good. I sincerely hope to receive your guidance.
