### ISSUE TITLE
Training immediately converges to white.

### ISSUE THREAD

**Issue by sungam94** [kwea123/nerf_pl#39]
Has anyone experienced a data set immediately (few hundred iterations) converging to white?
It's a 360 of a figurine like kwea123's featured in the README of this repo; with 50 photographs taken in front of a white background.
COLMAP has done a successful solve with all cams.
Does anyone have an idea how to debug?

**Comment by kwea123** [comment]
How do the images look like? Does the white background occupy most of the area?

**Comment by sungam94** [comment]
Hi kwea123,
thanks for sharing your work and the fast reply. Here is a screenshot:
![archer](https://user-images.githubusercontent.com/2469654/95739125-9a60fe00-0c8a-11eb-8e29-735d3babd6c7.png)

**Comment by kwea123** [comment]
Are you sure COLMAP has successfully resolved the poses? I've heard that too clean white background has a negative impact on the pose solution... you can check this using gui for example.
If the poses are indeed correct, then maybe try to increase the batch size (so that more samples from the object are drawn) or try other optimizers such as `radam` or `ranger`. A little more complicated solution can be found [here](https://github.com/bmild/nerf/issues/29)
