### ISSUE TITLE
Convert .pfm to depth map in meters

### ISSUE THREAD

**Issue by nemephist** [kwea123/nerf_pl#45]
Thanks a lot for your work!
Could you please explain, how to get depth map (in meters) from pfm data?
I've tried depth_map = 1/(1 - depth_pfm), but the result has a discrepancy with the ground truth as shown in attached image.
![image](https://user-images.githubusercontent.com/50966643/99523059-8e620d80-29a7-11eb-8523-56ad6a08ec4c.png)

**Comment by kwea123** [comment]
Is your data forward-facing? If yes, then your depth convertion `depth_real = 1/(1-depth_ndc)` is correct.
Concerning the scale discrepancy, it is reasonable that the real scale is unknown to COLMAP if you're not using stereo to constrain it. So COLMAP outputs a random scale, and nerf just learn to align to that scale, that's why the final scale is different from ground truth. 

If you really want to align it to ground truth, try to use some accurate depths (like the depths on the door) to figure out the optimal scale ratio between the prediction and the ground truth, and use that number to scale everything.
The final note is that nerf isn't explicitly trained to get good depth, so its depth is very noisy and unsmoothed. If you want smooth and accurate depth I recommend that you use multi-view stereo methods like MVSNet, or I have another implementation [here](https://github.com/kwea123/CasMVSNet_pl) you can refer to.

**Comment by nemephist** [comment]
Thanks for your reply!
Yes, my data is forward-facing. 
Then, I generated data with colmap model aligner (it align camera positions according given cameras extrinsics) and used imgs2poses.py from llff-repo to generate poses_bouns.npy. First train was unsuccessful, because the order of images in images.bin was broken after running colmap model aligner. I mean, that input images order was: 0,1,2... became 3,4,0... So, when we load data with [this](https://github.com/kwea123/nerf_pl/blob/master/datasets/llff.py#L176) script, images and poses poses and pictures lose right order. 
Next step I modifyed images2poses.py from llff repo and arrange pictures and poses in the correct order, add min and max depth from my ground truth depth maps. After training I still got discrepancy with GT.
I think it would be a good idea to figure out the optimal scale ratio relying on the GT, as you suggested. 
Once again I want to thank you for the quick response and advice about multi-view stereo methods

**Comment by YamamotoSayaka** [comment]
Hi @nemephist , here I'm also trying to apply nerf to some indoor environments.
However, when I tried in my data (which looks quite similar to yours), nerf always gives me noisy or blank results.
I checked the order of the input images as mentioned, and I'm sure it is correct.

I'm wondering if it's possible to share the above images/poses with me so I check the details?
Many thx in advance.

**Comment by nemephist** [comment]
Hi  @YamamotoSayaka)
I put my data [here](https://yadi.sk/d/hdsXWUQZo_VsRw?w=1). In input folder my input data,  output - few images after training and ckpts for my experiment.
How did you make poses_bounds.npy?
I still cannot compose correct poses_bounds.npy from my own data with known extrinsics:( Correct training results obtained just through colmap.

**Comment by YamamotoSayaka** [comment]
Hi @nemephist I captured my data with a depth sensor.
So I just calculate the pose bounds following llff code and the real depth data, 
i.e, the max depth + 2m and min depth - 2m, still not sure if this would be the problem.

maybe you can try to plot the poses in 3d with your extrinsics and results from colmap to check if they are different?
