### ISSUE TITLE
Unstable convergence PSNR

### ISSUE THREAD

**Issue by stc1995** [kwea123/nerf_pl#46]
Thanks for your reimplementation.
However, in my 5 trials of running the original training code of Lego, the results are unstable. In detail, 3 trials results are ended with PSNR in 9~10, the other two trials ended with PSNR above 30.
Did you encounter similar issues? Thanks for your response!

**Comment by kwea123** [comment]
It highly depends on the network initialization and the first training samples. Since there is a large portion of white background, if the network overfits to this background at the beginning, it makes the result very bad. You can see a solution [here](https://github.com/bmild/nerf/issues/29), or simply increase the batch size or trying other optimizers such as `radam` or `ranger` might help.
