### ISSUE TITLE
Incorrect color extraction. Any suggestion?

### ISSUE THREAD

**Issue by ash001234** [kwea123/nerf_pl#55]
Hi, thank for creating this repo and letting us to use our datasets.  I encountered color extraction issue with my 3D bag model. I followed your instructions from both of your youtube videos by changing the x,y,z min and max accordingly. 

xmin, xmax = -0.6, 0.7 # left/right range
ymin, ymax = -0.6, 0.7 # forward/backward range
zmin, zmax = -2, -0.7  # up/down range
sigma_threshold = 5. # controls the noise (lower=maybe more noise; higher=some mesh might be missing)

The following attached is the 3D model without color. 
![github_1]
(https://user-images.githubusercontent.com/78581569/106994578-09bda900-67b8-11eb-928b-3df1ab2693ea.PNG)

The following attached is the 3D model with color. 
![github_2](https://user-images.githubusercontent.com/78581569/106994808-789b0200-67b8-11eb-8547-06ab3569fc11.PNG)
![github_3](https://user-images.githubusercontent.com/78581569/106994818-7fc21000-67b8-11eb-9c21-5c83c68339aa.PNG)

I tried adjusting occ_threshold to 0.1 and also used --use_vertical_normal but the color is still incorrect. 
I also read posts from the past regarding color extraction but none of them work. 
My datasets contained 58 bag images trained with 30 epochs. 

Please advise me if I did anything incorrect. 

https://drive.google.com/drive/u/2/folders/1Lm2efzJIAjeIYPMn4deJ8GWH1al95L5w

Thank you!

**Comment by kwea123** [comment]
can you provide the checkpoint?

**Comment by ash001234** [comment]
https://drive.google.com/drive/u/2/folders/17Oy2b3HQnlBxYnCd1uD2dloKRdTA3Rwm

I named it as silica.ckpt too.

**Comment by kwea123** [comment]
This one is locked I cannot see. Can you put into the first folder?

**Comment by ash001234** [comment]
Ops sorry. I have moved it to the first folder.

**Comment by kwea123** [comment]
Hi, thanks for letting me find out the problem. It is because I use different libraries to read the image in training (PIL) and evaluation (opencv). For your images the rotation is different: PIL reads horizontally and opencv reads vertically.

The fix is pushed to master and dev. Please pull and run again.
![Screenshot from 2021-02-05 16-26-50](https://user-images.githubusercontent.com/11364490/107002717-ff5ad980-67ce-11eb-8fc8-5e256f3db8ff.png)
This is what I get. The details are missing, but the color in general is correct.
