### ISSUE TITLE
Colmap does not complete on colab notbeook.

### ISSUE THREAD

**Issue by kurtjcu** [kwea123/nerf_pl#56]
Hi,
the current builds of colmap seem to have some issues, currently they fail in imgs2poses.py. Currently I had mine work with a win version of colmap and imgs2poses using the pre generated sparse data. 

can reproduce the issue by running the colmap colab notebook in the main readme.

**Comment by kwea123** [comment]
So COLMAP completes but not `img2poses.py`, is that correct. Sometimes COLMAP might fail to reconstruct all images, for example if there are too few feature points, too much textureless region (white background), etc. `imgs2poses.py` assumes that every image is reconstructed so that leads to an error.

I suggest that you retake cleaner images according to common [photogrammetry guidelines](https://www.google.com/search?q=photogrammetry+guidelines&oq=photogrammetry+guidelines&aqs=chrome..69i57&sourceid=chrome&ie=UTF-8) and try again.
