### ISSUE TITLE
down right back to right up back conversion in llff.py

### ISSUE THREAD

**Issue by hturki** [kwea123/nerf_pl#58]
**Describe the bug**
I'm trying to make sure that I understand the purpose of https://github.com/kwea123/nerf_pl/blob/dev/datasets/llff.py#L198. In particular, we're changing the coordinate system of the rotation matrix R but not of the translation vector, which remains in "down right back" coordinates - is that intentional?

Also https://github.com/bmild/nerf/issues/34 suggests that this is mainly intended for forward facing scenes where we're using NDC, but if I'm interpreting the code correctly this transformation still happens for 360 scenes. Is that intentional and desired behavior?

**Which branch you use**
dev

**Comment by kwea123** [comment]
This is not specific to NDC, but for all scenes constructed using COLMAP, which is desired behavior. Actually this conversion has relation with this part:
https://github.com/kwea123/nerf_pl/blob/20d1670b2d6d64e8f2bde65e263531f7af5779a5/datasets/ray_utils.py#L5-L24

When we generate camera rays, the current code assumes "right up back" camera coordinate. Take the upper left (0, 0) pixel for example, its ray will have direction in (-x, +y, -z) under this code.

That means you can omit the coordinate conversion, but if you do so you have to rewrite the `get_ray_directions` function to correctly generate rays in your coordinate system. Btw, the translation vector has nothing to do here, since it's the camera's position in world coordinate, so it won't change. Remember that we are changing **how is the camera rotated w.r.t. the world** only.

The author mentioned NDC because this conversion is indispensable for the reasons he stated in that post. 360 scenes do not necessary require this conversion, but having the same conversion leads to same code and more conciseness, so I adopted this conversion for both settings.

**Comment by hturki** [comment]
Thanks for the clarification. Just to confirm, this repo doesn't actually do the alternate pose conversion for spheric poses detailed in https://github.com/bmild/nerf/blob/55d8b00244d7b5178f4d003526ab6667683c9da9/load_llff.py#L184 (and just calls the same center_poses method for both forward-facing and 360 scenes?)
