### ISSUE TITLE
rays_d is not a unit vector when we use NDC space

### ISSUE THREAD

**Issue by zjjMaiMai** [kwea123/nerf_pl#65]
https://github.com/kwea123/nerf_pl/blob/b7e44f661b9c391cf10760bf19b9243c019cfbe8/datasets/llff.py#L238

**Comment by kwea123** [comment]
When using NDC space, we cannot normalize the vector in order to correctly sample the depths from 1 to infinity. Please see the original paper's write up.

I was also confused in this part, but after some experiments, I find that there is actually no need to normalize the view vectors - even for real space - since the sigma will be learnt according to the view vector's magnitude. E.g. if the vectors have norm 2, then  the network would just learn the sigma to be 1/2 of the original value, to make the final alpha the same.
https://github.com/kwea123/nerf_pl/blob/34568e2b9574e99508feaeecf9567f968b53edf9/models/rendering.py#L138
