### ISSUE TITLE
GPU available: Faile,used:Faile

### ISSUE THREAD

**Issue by stone100010** [kwea123/nerf_pl#7]
It's a great honor to see your project. I started training at 20:40 last night, but I haven't finished it yet. Ckpts / exp / epoch = 0.ckpt and epoch = 1.ckpt. Why is the GPU connection wrong? I used two computers, rtx2080ti and Titan RTX

**Comment by kwea123** [comment]
This is installation problem, and has nothing to with the code. As the title says, your gpus are not visible, and you're using cpu to train, that's why it's so slow. Please review your installation of cuda/cudnn etc. I saw in the previous post you use docker, in that case check your dockerfile, and run `nvidia-smi` to check if cuda is correctly installed.

You can find many resource on the installation online, here is not the correct place to ask. If you still want to consult me personally, you can email me, but I'm afraid a detailed consultancy is not free.
