### ISSUE TITLE
NeRF：dists = dists * tf.linalg.norm(rays_d[..., None, :], axis=-1)

### ISSUE THREAD

**Issue by shuochen365** [kwea123/nerf_pl#80]
Hi,

Why multiply each distance by the norm of the light in its corresponding direction to convert it into a real-world distance?

> dists = dists * tf.linalg.norm(rays_d[..., None, :], axis=-1)

Can you explain the principle behind it？

Thanks.

**Comment by kwea123** [comment]
In volume rendering theory, the opacity of a point is defined by its occupancy (sigma) and how long the light has traveled until that point (the distance). So in theory we need to multiply them together to compute alpha correctly.
If you are asking for NDC however, I am not sure of the correct implementation, because in theory we need to convert everything back to euclidean space first, but in practice it seems that the we can simply use the distance in NDC, and whether multiplying by the distance or not doesn't matter (I don't in my implementation). In my understanding the sigma learnt in this way doesn't correspond to its physical meaning anymore, but kind of "pseudo-occupancy". I'm not sure how to explain this anyways.

**Comment by shuochen365** [comment]
Thank you very much for your reply
