### ISSUE TITLE
Display trained nerf-w model in VR headset

### ISSUE THREAD

**Issue by jb892** [kwea123/nerf_pl#86]
Hi @kwea123, 

Thanks for sharing your implementation of nerf-w. I'm new to this field. So, your code really helps me a lot. 
I was wondering if it is possible to display the pre-trained nerf-w model (on the Phototourism dataset) via a VR headset (Oculus rift) and render it in real-time (at least 15fps)? Have you done anything like this before? Or any suggestion and tips from you would be much appreciated!

**Comment by kwea123** [comment]
Hi, the current implementation is not fast enough to run in real-time (it runs at 30s per image...). For faster inference, you might need to check some other works like [PlenOctree](https://alexyu.net/plenoctrees/) [NVSF](https://lingjie0206.github.io/papers/NSVF/)

For VR usage, I believe it shouldn't be that difficult porting to game engines like Unity or Unreal. I have some examples (not VR, just normal display) on Unity, you can check [nerf_Unity](https://github.com/kwea123/nerf_Unity). I think here you need much expertise in VR programming since to my knowledge this is an application that no one has ever developed (publicly).

**Comment by jb892** [comment]
Hi @kwea123,

After reading through your comment, I think it would be too difficult for me to establish a Nerf-w application running in real-time at this stage. So, I decided to start with something very simple. By just inferencing a video sequence of  a trained model and render that video in VR headset. Then, maybe I would start to figure out how to speed up the inferencing by borrowing ideas from PlenOctree and NVSF.

Thanks for your suggestions! Have a nice day!
